/* Q7 — Mixed predicate query (count-only) */
/* KEY TYPE: LowCardinality(String) */
/* SCHEMA: timeseriesdata(name LowCardinality(String), timestamp DateTime64(3)) */

SELECT
  count() AS cnt
FROM timeseriesdata
WHERE name IN (
    'EDFT.SPECTACULAR.CORGI.ARCHETYPAL.MOTH.SKILLED.VIPER.LEMON.CHINCH.EDFT',
    'EDFT.IMAGINARY.HUSKY.PORCELAIN.ROOK.VERSED.DUCK.HONEST.WREN.THUND.EDFT',
    'EDFT.MANIPULATIVE.NAUTILUS.ACTIVE.CUTTLEFISH.ACCELERATED.CARP.PAP.EDFT',
    'EDFT.ORIGINAL.FENNEC.INVISIBLE.GOAT.STRIPED.TORTOISE.PRECISE.STUR.EDFT',
    'EDFT.QUARTZ.ASP.STRIPED.CRICKET.QUIET.AARDWARK.HOSPITABLE.FINCH.R.EDFT'
  )
  AND timestamp >= toDateTime('2025-12-14')
  AND timestamp <  toDateTime('2025-12-18')